import { simpleNamedColorToPixelColor } from '../../util/color';
import type { PixelColor } from '../types';

export const WPLACE_COLORS: PixelColor[] = [
    { name: 'Transparent', rgba: 0x00000000 },
    { name: 'Black', rgba: 0xff000000 },
    { name: 'Dark Gray', rgba: 0xff3c3c3c },
    { name: 'Gray', rgba: 0xff787878 },
    { name: 'Light Gray', rgba: 0xffd2d2d2 },
    { name: 'White', rgba: 0xffffffff },
    { name: 'Deep Red', rgba: 0xff180060 },
    { name: 'Red', rgba: 0xff241ced },
    { name: 'Orange', rgba: 0xff277fff },
    { name: 'Gold', rgba: 0xff09aaf6 },
    { name: 'Yellow', rgba: 0xff3bddf9 },
    { name: 'Light Yellow', rgba: 0xffbcfaff },
    { name: 'Dark Green', rgba: 0xff68b90e },
    { name: 'Green', rgba: 0xff7be613 },
    { name: 'Light Green', rgba: 0xff5eff87 },
    { name: 'Dark Teal', rgba: 0xff6e810c },
    { name: 'Teal', rgba: 0xffa6ae10 },
    { name: 'Light Teal', rgba: 0xffbee113 },
    { name: 'Dark Blue', rgba: 0xff9e5028 },
    { name: 'Blue', rgba: 0xffe49340 },
    { name: 'Cyan', rgba: 0xfff2f760 },
    { name: 'Indigo', rgba: 0xfff6506b },
    { name: 'Light Indigo', rgba: 0xfffbb199 },
    { name: 'Dark Purple', rgba: 0xff990c78 },
    { name: 'Purple', rgba: 0xffb938aa },
    { name: 'Light Purple', rgba: 0xfff99fe0 },
    { name: 'Dark Pink', rgba: 0xff7a00cb },
    { name: 'Pink', rgba: 0xff801fec },
    { name: 'Light Pink', rgba: 0xffa98df3 },
    { name: 'Dark Brown', rgba: 0xff344668 },
    { name: 'Brown', rgba: 0xff2a6895 },
    { name: 'Beige', rgba: 0xff77b2f8 },
    { name: 'Medium Gray', rgba: 0xffaaaaaa },
    { name: 'Dark Red', rgba: 0xff1e0ea5 },
    { name: 'Light Red', rgba: 0xff7280fa },
    { name: 'Dark Orange', rgba: 0xff1a5ce4 },
    { name: 'Light Tan', rgba: 0xff94b5d6 },
    { name: 'Dark Goldenrod', rgba: 0xff31849c },
    { name: 'Goldenrod', rgba: 0xff31adc5 },
    { name: 'Light Goldenrod', rgba: 0xff5fd4e8 },
    { name: 'Dark Olive', rgba: 0xff3a6b4a },
    { name: 'Olive', rgba: 0xff4a945a },
    { name: 'Light Olive', rgba: 0xff73c584 },
    { name: 'Dark Cyan', rgba: 0xff9f790f },
    { name: 'Light Cyan', rgba: 0xfff2fabb },
    { name: 'Light Blue', rgba: 0xffffc77d },
    { name: 'Dark Indigo', rgba: 0xffb8314d },
    { name: 'Dark Slate Blue', rgba: 0xff84424a },
    { name: 'Slate Blue', rgba: 0xffc4717a },
    { name: 'Light Slate Blue', rgba: 0xfff1aeb5 },
    { name: 'Light Brown', rgba: 0xff63a4db },
    { name: 'Dark Beige', rgba: 0xff5180d1 },
    { name: 'Light Beige', rgba: 0xffa5c5ff },
    { name: 'Dark Peach', rgba: 0xff49529b },
    { name: 'Peach', rgba: 0xff7880d1 },
    { name: 'Light Peach', rgba: 0xffa4b6fa },
    { name: 'Dark Tan', rgba: 0xff52637b },
    { name: 'Tan', rgba: 0xff6b849c },
    { name: 'Dark Slate', rgba: 0xff413933 },
    { name: 'Slate', rgba: 0xff8d756d },
    { name: 'Light Slate', rgba: 0xffd1b9b3 },
    { name: 'Dark Stone', rgba: 0xff3f646d },
    { name: 'Stone', rgba: 0xff6b8c94 },
    { name: 'Light Stone', rgba: 0xff9ec5cd },
].map(({ name, rgba }) => simpleNamedColorToPixelColor(name, rgba));
