import type { PixelColor } from '../types';
import { rgbaRawToHexWithAlpha } from '../../util/color';

export const BPLACE_COLORS: PixelColor[] = [
    { name: 'Pastel red', rgba: 0xffcecefd },
    { name: 'Light red', rgba: 0xffa5a5fc },
    { name: 'Red', rgba: 0xff4444ef },
    { name: 'Dark red', rgba: 0xff1c1cb9 },
    { name: 'Deep red', rgba: 0xff1d1d7f },
    { name: 'Pastel orange', rgba: 0xffc2e5ff },
    { name: 'Light orange', rgba: 0xff74bafd },
    { name: 'Orange', rgba: 0xff1673f9 },
    { name: 'Dark orange', rgba: 0xff0c41c2 },
    { name: 'Deep orange', rgba: 0xff122d7c },
    { name: 'Pastel yellow', rgba: 0xffaff7fe },
    { name: 'Light yellow', rgba: 0xff4dd3fc },
    { name: 'Yellow', rgba: 0xff08b3ea },
    { name: 'Dark yellow', rgba: 0xff0762a1 },
    { name: 'Deep yellow', rgba: 0xff123f71 },
    { name: 'Pastel lime', rgba: 0xffb7fbe5 },
    { name: 'Light lime', rgba: 0xff64f2be },
    { name: 'Lime', rgba: 0xff16cc84 },
    { name: 'Dark lime', rgba: 0xff0f7c4d },
    { name: 'Deep lime', rgba: 0xff145336 },
    { name: 'Pastel green', rgba: 0xffdcfbcb },
    { name: 'Light green', rgba: 0xffacef86 },
    { name: 'Green', rgba: 0xff5ec522 },
    { name: 'Dark green', rgba: 0xff3d8015 },
    { name: 'Deep green', rgba: 0xff2d5314 },
    { name: 'Pastel teal', rgba: 0xffecf9b8 },
    { name: 'Light teal', rgba: 0xffd4ea5e },
    { name: 'Teal', rgba: 0xffa6b814 },
    { name: 'Dark teal', rgba: 0xff6e760f },
    { name: 'Deep teal', rgba: 0xff4a4e13 },
    { name: 'Pastel cyan', rgba: 0xfffefacf },
    { name: 'Light cyan', rgba: 0xfff9e867 },
    { name: 'Cyan', rgba: 0xffd4b606 },
    { name: 'Dark cyan', rgba: 0xff90740e },
    { name: 'Deep cyan', rgba: 0xff634e16 },
    { name: 'Pastel blue', rgba: 0xffffdfbd },
    { name: 'Light blue', rgba: 0xfffdc593 },
    { name: 'Blue', rgba: 0xfff6823b },
    { name: 'Dark blue', rgba: 0xffd84e1d },
    { name: 'Deep blue', rgba: 0xff8a3a1e },
    { name: 'Pastel indigo', rgba: 0xffffd8cc },
    { name: 'Light indigo', rgba: 0xfffcb4a5 },
    { name: 'Indigo', rgba: 0xfff16663 },
    { name: 'Dark indigo', rgba: 0xffca3843 },
    { name: 'Deep indigo', rgba: 0xff812e31 },
    { name: 'Pastel violet', rgba: 0xfffdd3db },
    { name: 'Light violet', rgba: 0xfffdb5c4 },
    { name: 'Violet', rgba: 0xfff65c8b },
    { name: 'Dark violet', rgba: 0xffd9286d },
    { name: 'Deep violet', rgba: 0xff951d4c },
    { name: 'Pastel fuchsia', rgba: 0xffffd1f5 },
    { name: 'Light fuchsia', rgba: 0xfffcabf0 },
    { name: 'Fuchsia', rgba: 0xffef46d9 },
    { name: 'Dark fuchsia', rgba: 0xffaf1ca2 },
    { name: 'Deep fuchsia', rgba: 0xff751a70 },
    { name: 'Pastel pink', rgba: 0xffefd6fa },
    { name: 'Light pink', rgba: 0xffd4a8f9 },
    { name: 'Pink', rgba: 0xff9948ec },
    { name: 'Dark pink', rgba: 0xff5d18be },
    { name: 'Deep pink', rgba: 0xff431883 },
    { name: 'Pastel rose', rgba: 0xffd7d1ff },
    { name: 'Light rose', rgba: 0xffafa4fd },
    { name: 'Rose', rgba: 0xff5e3ff4 },
    { name: 'Dark rose', rgba: 0xff3c12be },
    { name: 'Deep rose', rgba: 0xff371388 },
    { name: 'Pastel skin tone', rgba: 0xffe0e4f5 },
    { name: 'Light skin tone', rgba: 0xffbac3e8 },
    { name: 'Skin tone', rgba: 0xff6478b4 },
    { name: 'Dark skin tone', rgba: 0xff3a5488 },
    { name: 'Deep skin tone', rgba: 0xff1c2b4a },
    { name: 'Pastel brown', rgba: 0xffd1deea },
    { name: 'Light brown', rgba: 0xffaec3dc },
    { name: 'Brown', rgba: 0xff4875a8 },
    { name: 'Dark brown', rgba: 0xff29527f },
    { name: 'Deep brown', rgba: 0xff19324d },
    { name: 'Pastel mud', rgba: 0xffd9e0e3 },
    { name: 'Light mud', rgba: 0xffbfc9cd },
    { name: 'Mud', rgba: 0xff6b8089 },
    { name: 'Dark mud', rgba: 0xff495c64 },
    { name: 'Deep mud', rgba: 0xff2d393e },
    { name: 'Pastel gray', rgba: 0xfff6f4f3 },
    { name: 'Light gray', rgba: 0xffdbd5d1 },
    { name: 'Gray', rgba: 0xff80726b },
    { name: 'Dark gray', rgba: 0xff514137 },
    { name: 'Deep gray', rgba: 0xff271811 },
    { name: 'White', rgba: 0xffffffff },
    { name: 'Black', rgba: 0xff000000 },
    { name: 'Gold', rgba: 0xff228fca },
    { name: 'Transparent', rgba: 0x00000000 },
    { name: 'Silver', rgba: 0xff7f7f7f },
    { name: 'Holographic', rgba: 0xffffaecf },
    { name: 'Dark Holographic', rgba: 0xff261019 },
].map(({ name, rgba }) => ({ name, rgba, hex: rgbaRawToHexWithAlpha(rgba) }));
