import { rgbaRawToHexWithAlpha } from '../../util/color';
import type { PixelColor } from '../types';

export const BPLACE_COLORS: PixelColor[] = [
    { name: 'Pastel red', rgba: 0xffd1d1ff },
    { name: 'Light red', rgba: 0xffa2a2ff },
    { name: 'Red', rgba: 0xff2c2cfb },
    { name: 'Dark red', rgba: 0xff0000c1 },
    { name: 'Deep red', rgba: 0xff121263 },
    { name: 'Pastel orange', rgba: 0xffc2e2ff },
    { name: 'Light orange', rgba: 0xff75b6ff },
    { name: 'Orange', rgba: 0xff0073ff },
    { name: 'Dark orange', rgba: 0xff0041c2 },
    { name: 'Deep orange', rgba: 0xff002266 },
    { name: 'Pastel yellow', rgba: 0xffa3f4ff },
    { name: 'Light yellow', rgba: 0xff66e5ff },
    { name: 'Yellow', rgba: 0xff00ccff },
    { name: 'Dark yellow', rgba: 0xff007ebd },
    { name: 'Deep yellow', rgba: 0xff003d5c },
    { name: 'Pastel lime', rgba: 0xffbcfbe5 },
    { name: 'Light lime', rgba: 0xff68f3c2 },
    { name: 'Lime', rgba: 0xff00cf7c },
    { name: 'Dark lime', rgba: 0xff007d53 },
    { name: 'Deep lime', rgba: 0xff003d29 },
    { name: 'Pastel green', rgba: 0xffd9f9c7 },
    { name: 'Light green', rgba: 0xffa8f17b },
    { name: 'Green', rgba: 0xff50c900 },
    { name: 'Dark green', rgba: 0xff317500 },
    { name: 'Deep green', rgba: 0xff1b3508 },
    { name: 'Pastel teal', rgba: 0xfff0fbc6 },
    { name: 'Light teal', rgba: 0xffdff174 },
    { name: 'Teal', rgba: 0xffacc700 },
    { name: 'Dark teal', rgba: 0xff647800 },
    { name: 'Deep teal', rgba: 0xff2f3800 },
    { name: 'Pastel cyan', rgba: 0xfffffbcd },
    { name: 'Light cyan', rgba: 0xfffff185 },
    { name: 'Cyan', rgba: 0xffe2d004 },
    { name: 'Dark cyan', rgba: 0xff857b08 },
    { name: 'Deep cyan', rgba: 0xff453f0c },
    { name: 'Pastel blue', rgba: 0xffffe3cc },
    { name: 'Light blue', rgba: 0xffffc58e },
    { name: 'Blue', rgba: 0xffff7f2b },
    { name: 'Dark blue', rgba: 0xffdd4413 },
    { name: 'Deep blue', rgba: 0xff622713 },
    { name: 'Pastel indigo', rgba: 0xffffdfd6 },
    { name: 'Light indigo', rgba: 0xffffb3a3 },
    { name: 'Indigo', rgba: 0xffff5f61 },
    { name: 'Dark indigo', rgba: 0xffb8392e },
    { name: 'Deep indigo', rgba: 0xff602a20 },
    { name: 'Pastel violet', rgba: 0xffffdbe7 },
    { name: 'Light violet', rgba: 0xffffb4cd },
    { name: 'Violet', rgba: 0xffff518b },
    { name: 'Dark violet', rgba: 0xffcf076b },
    { name: 'Deep violet', rgba: 0xff660f3b },
    { name: 'Pastel fuchsia', rgba: 0xffffdbf8 },
    { name: 'Light fuchsia', rgba: 0xffffa8f4 },
    { name: 'Fuchsia', rgba: 0xfff431dc },
    { name: 'Dark fuchsia', rgba: 0xffad009f },
    { name: 'Deep fuchsia', rgba: 0xff580e54 },
    { name: 'Pastel pink', rgba: 0xffedd9fd },
    { name: 'Light pink', rgba: 0xffd5a5fd },
    { name: 'Pink', rgba: 0xff9a2ffa },
    { name: 'Dark pink', rgba: 0xff5c00c6 },
    { name: 'Deep pink', rgba: 0xff320c64 },
    { name: 'Pastel rose', rgba: 0xffe4d6ff },
    { name: 'Light rose', rgba: 0xffc0a1ff },
    { name: 'Rose', rgba: 0xff6a20ff },
    { name: 'Dark rose', rgba: 0xff3f00bd },
    { name: 'Deep rose', rgba: 0xff270070 },
    { name: 'Pastel skin tone', rgba: 0xffd7e1f4 },
    { name: 'Light skin tone', rgba: 0xffacc0e7 },
    { name: 'Skin tone', rgba: 0xff5e7dba },
    { name: 'Dark skin tone', rgba: 0xff3a5488 },
    { name: 'Deep skin tone', rgba: 0xff1f2d4a },
    { name: 'Pastel brown', rgba: 0xffdbedfa },
    { name: 'Light brown', rgba: 0xff94bae0 },
    { name: 'Brown', rgba: 0xff407cbf },
    { name: 'Dark brown', rgba: 0xff224f87 },
    { name: 'Deep brown', rgba: 0xff09284e },
    { name: 'Pastel mud', rgba: 0xffd7e5ec },
    { name: 'Light mud', rgba: 0xffadc3cc },
    { name: 'Mud', rgba: 0xff618696 },
    { name: 'Dark mud', rgba: 0xff41606f },
    { name: 'Deep mud', rgba: 0xff233c43 },
    { name: 'Pastel gray', rgba: 0xffe6e4e4 },
    { name: 'Light gray', rgba: 0xffcac4c4 },
    { name: 'Gray', rgba: 0xff8d8182 },
    { name: 'Dark gray', rgba: 0xff5b4d4e },
    { name: 'Deep gray', rgba: 0xff2a2223 },
    { name: 'White', rgba: 0xffffffff },
    { name: 'Black', rgba: 0xff000000 },
    { name: 'Gold', rgba: 0xff228fca },
    { name: 'Transparent', rgba: 0x00000000 },
    { name: 'Silver', rgba: 0xff7f7f7f },
    { name: 'Holographic', rgba: 0xffffaecf },
    { name: 'Dark Holographic', rgba: 0xff261019 },
].map(({ name, rgba }) => ({ name, rgba, hex: rgbaRawToHexWithAlpha(rgba) }));
